# Generated by Django 5.0.6 on 2024-06-03 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_q', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet_q',
            name='video_url',
            field=models.URLField(default=django.utils.timezone.now),
        ),
    ]
